version: 2.1

jobs:
  unit-tests:
    docker: 
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: install nodejs
          command: |
            wget http://nodejs.org/dist/v0.8.2/node-v0.8.2.tar.gz
            tar -zxf node-v0.8.01.tar.gz
            cd node-v0.6.18
            ./configure
            make
            sudo make install
      - run:
          name: npm install
          command: npm install
      # - run:
      #     name: Runnning tests
      #     command: npm test
  build-android:
    docker:
      # - image: circleci/node:10.13.0
      - image: circleci/
    environment:
      ANDROID_SDK_HOME: /opt/android/sdk
    steps:
      # - checkout
      - run:
          name: pwd
          command: pwd && cd /opt/ && pwd && ls -al
      # - run:
      #     name: remove folders
      #     command: rm -rf plugins/ platforms/ www/
      # - run:
      #       name: npm gobal
      #       command: sudo npm install -g ionic cordova
      # - run:
      #       name: npm install
      #       command: npm install
      # - run:
      #     name: build android apk
      #     command: ionic cordova build android --no-interactive
      # - run:
      #     name: copy artifact
      #     command: cp -r platforms/android/build/outputs/apk $CIRCLE_ARTIFACTS
      # - run: cd ../../.. && ls
      # - run: cd /usr/ && cd bin && ls
      # - run: cd /usr/ && cd lib && ls
      # - run: cd /usr/ && cd local && ls
      # - run: cd /usr/ && cd src && ls

workflows:
  version: 2.1
  pre-and-build:
    jobs:
      - unit-tests
      - build-android:
          requires:
            - unit-tests