## Customize the test machine
machine:
    timezone:
        Europe/Paris # Set the timezone

    environment:
        XCODE_SCHEME: symbolicator
        XCODE_WORKSPACE: symbolicator

## Customize dependencies
dependencies:
    pre:
        - npm install -g typescript typings ionic cordova ios-sim ios-deploy
        - typings install

    post:
        - ionic platform add ios

## customize test commands
test:
    override:
        - ionic cordova build ios --no-interactive

deployment:
    beta_distribution:
        branch: 'master'
        commands:
            - cp -R ./dist $CIRCLE_ARTIFACTS