version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.13.0
      - checkout # check out the code in the project directory
      - run: npm install 
      - run:
          name: Runnning tests
          command: npm test