version: 2.1

jobs:
  unit-tests:
    docker: 
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: Runnning tests
          command: npm test
  build-android:
    docker:
      - image: circleci/node:10.13.0
      - image: circleci/android:api-28-alpha 
    steps:
      - checkout
      - run:
          name: remove folders
          command: rm -rf plugins/ platforms/ www/
      - run:
            name: npm install
            command: npm install
      - run:
          name: build android apk
          command: ionic cordova build android --no-interactive
      - run:
          name: copy artifact
          command: cp -r platforms/android/build/outputs/apk $CIRCLE_ARTIFACTS



workflows:
  version: 2.1
  pre-and-build:
    jobs:
      - unit-tests
      - build-android:
          requires:
            - unit-tests